# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://keepsimpler.github.io/putixin/"

git_url = "https://github.com/keepsimpler/putixin/tree/master/"

def custom_doc_links(name): return None
